# Generated by Django 5.0.5 on 2024-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_activity_image_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Men'), (1, 'Women'), (2, 'Both')], default=2),
        ),
    ]
