# Generated by Django 5.0.5 on 2024-05-09 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_featureproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
