# Generated by Django 5.0.5 on 2024-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_featureproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='fallback.jpg', upload_to='product/'),
        ),
    ]
