# Generated by Django 5.0.5 on 2024-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_order_ordered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
    ]
