# Generated by Django 5.0.5 on 2024-05-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
